# Generated by Django 5.0.4 on 2024-05-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код учёта'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_code_flag',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='без имени'),
        ),
    ]
