# Generated by Django 5.0.4 on 2024-05-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_user_registration_code_user_registration_code_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_code',
        ),
    ]
